Repository robotframework/SeleniumLibrary, pull requests merged in 2023-11, with the labels that each got.

#1821 Improve documentation on page load timeout
  src/SeleniumLibrary/__init__.py
  src/SeleniumLibrary/keywords/browsermanagement.py
  utest/test/api/approved_files/PluginDocumentation.test_many_plugins.approved.txt
  utest/test/api/approved_files/PluginDocumentation.test_parse_plugin_init_doc.approved.txt
Labels: enhancement, priority: medium, acknowledge

#1858 Remove deprecated headless option for chrome and firefox.
  src/SeleniumLibrary/keywords/webdrivertools/webdrivertools.py
Labels: bug, priority: critical, acknowledge

#1859 Mutable default value 1817
  .github/workflows/CI.yml
  src/SeleniumLibrary/keywords/browsermanagement.py
Labels: bug, priority: high, acknowledge

#1872 fix: Selenium CI badge show wrong status
  README.rst
Labels: priority: medium, acknowledge

#1741 Added minimize keyword
  atest/acceptance/windows.robot
  src/SeleniumLibrary/keywords/window.py
  utest/test/api/test_plugins.py
Labels: in progress
